// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ai_SsuWoOHMc1-pTdqflcin5azQwrCo',
    appId: '1:932223642584:web:a6da3b44e6c97265cf20ad',
    messagingSenderId: '932223642584',
    projectId: 'wechat-9f96b',
    authDomain: 'wechat-9f96b.firebaseapp.com',
    storageBucket: 'wechat-9f96b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCys9xSVy7Y1MN2RhJVc29FNJ2G0nah6Ok',
    appId: '1:932223642584:android:f5e0026ae3c40f65cf20ad',
    messagingSenderId: '932223642584',
    projectId: 'wechat-9f96b',
    storageBucket: 'wechat-9f96b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxgF5hzWAy-fDsmVGuyAuD6pa9136nSPo',
    appId: '1:932223642584:ios:d4158f349e583c93cf20ad',
    messagingSenderId: '932223642584',
    projectId: 'wechat-9f96b',
    storageBucket: 'wechat-9f96b.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
